// Demo mode for the public /demo console: answers the same API calls the real console makes,
// from app/lib/demo-data.json. That file is generated by scripts/build_demo_data.py by running
// the REAL engine against a copy of data/site.db, so every reply shown here is one the product
// actually produces. Nothing is sent to the backend and nothing is written.
import data from "./demo-data.json";

type Step = { text?: string; decision?: string; response: Record<string, unknown> };
const FLOWS = data.flows as unknown as Record<string, Step[]>;

let demoMode = false;
export const isDemo = () => demoMode;
export function setDemoMode(on: boolean) {
  demoMode = on;
}

export const DEMO_LIVE = data.live as unknown as {
  script: { who: "You" | "Vesper"; text: string }[];
  engine: Record<string, unknown> | null;
  brief: Record<string, unknown>;
};

/** Prompts the demo can answer; shown as chips in Talk. */
export const DEMO_PROMPTS = Object.values(FLOWS).map((f) => f[0].text as string);

const norm = (t: string) => t.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

let flow: Step[] | null = null;
let cursor = 0;

function nextStep(match: (s: Step) => boolean): Step | null {
  // continue the current flow first ("and at E-2?", "raise NCR"), else start a new one
  if (flow) {
    const i = flow.findIndex((s, idx) => idx >= cursor && match(s));
    if (i >= 0) {
      cursor = i + 1;
      return flow[i];
    }
  }
  for (const f of Object.values(FLOWS)) {
    if (match(f[0])) {
      flow = f;
      cursor = 1;
      return f[0];
    }
  }
  return null;
}

function fallback(text: string) {
  return {
    sessionId: "demo",
    state: "capturing",
    kind: "answer",
    reply: {
      text: `This is the recorded demo, so I can only replay prepared turns. Try one of the suggested prompts — or sign in to ask anything about the site. (You said: "${text}")`,
    },
    entities: [],
    contradictions: [],
    blockers: [],
    missing: [],
    allowedDecisions: [],
    events: ["demo_fallback"],
  };
}

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));

export async function mockReq(path: string, init?: RequestInit): Promise<unknown> {
  await delay(path === "/api/turn" || path === "/api/decision" ? 450 : 120); // feel like a network
  let body: Record<string, unknown> = {};
  if (typeof init?.body === "string") body = JSON.parse(init.body);
  else if (init?.body instanceof FormData) body = Object.fromEntries(init.body.entries());

  switch (path.split("?")[0]) {
    case "/api/health":
      return data.health;
    case "/api/session":
      flow = null;
      return { sessionId: "demo", commandLimit: null, commandsUsed: 0 };
    case "/api/bootstrap-demo":
      return { seeded: false };
    case "/api/voice/status":
      return { enabled: true, reachable: true, enrolled: true, threshold: 0.7 };
    case "/api/voice/enroll":
      return { enrolled: true, samples: 3, dims: 192, cohesion: 0.93 };
    case "/api/turn": {
      const text = String(body.text ?? "");
      const step = nextStep((s) => !!s.text && norm(s.text) === norm(text));
      return step ? { ...step.response, speaker: { match: true, score: 0.86 } } : fallback(text);
    }
    case "/api/decision": {
      const step = nextStep((s) => s.decision === body.decision);
      return step?.response ?? { state: "capturing", reply: { text: "Nothing to decide in this demo step." }, logged: null, allowedDecisions: [] };
    }
    case "/api/observations":
      return data.observations;
    case "/api/conversations":
      return { sessions: data.conversations, commandLimit: null, commandsUsed: 0 };
    case "/api/scenarios/run":
      return data.scenarios;
    case "/api/scenarios":
      return (data.scenarios as { results: { id: string; title: string }[] }).results.map((r) => ({ id: r.id, title: r.title }));
    case "/api/rtc/token":
      throw Object.assign(new Error("Live voice needs sign-in; the demo replays a recorded conversation."), { status: 503 });
    default:
      if (path.startsWith("/api/observations/")) {
        const id = decodeURIComponent(path.split("/").pop() ?? "");
        return (data.observations as { observation_id: string }[]).find((o) => o.observation_id === id) ?? null;
      }
      return null;
  }
}
